OpenLiberty/guides-common

- finish.adoc
(need to config SSH, so I branched off in the browser)
Please review change.
Is something missing or broken?
After you approve, I will let you merge. 
Resolves https://github.com/OpenLiberty/guides-common/issues/36 and OpenLiberty/iguides-common#98
> change to contribute section

- kube-prereq.adoc
- kube-start.adoc
Introduce shared sections that will be used for Kubernetes guides such as what is discussed in this PR: https://github.com/OpenLiberty/draft-guide-kubernetes-microprofile-config/pull/2
> Add Kubernetes shared docs

- kube-start.adoc
https://github.com/OpenLiberty/draft-guide-kubernetes/issues/51
> Remove minikube stop and delete statement

- kube-prereq.adoc
It may be a bit confusing to read this sentence as Docker for Windows/Mac is the only option on Windows/Mac.
> Update kube-prereq to ask user to upgrade if facing issues

- kube-prereq.adoc
- kube-start.adoc
https://github.com/OpenLiberty/draft-guide-kubernetes-microprofile-config/issues/12
> Apply ID review feedback for Kube/MpConfig guide

- kube-minikube-teardown.adoc
Add teardown instructions for Minikube.
> Add minikube teardown instructions

- gitclone.adoc
- kube-minikube-teardown.adoc
- kube-prereq.adoc
- kube-start.adoc
Fix: https://github.com/OpenLiberty/guides-common/issues/99#issuecomment-459816019
> ID Review Istio

- kube-minikube-teardown.adoc
> Fix numbered list error in kube teardown

- kube-prereq.adoc
Change "container types" to "container runtimes".  "Container runtimes" is the right term.
> "container types" should be "container runtimes"

- guide_prereqs.json
> Merge qa to master: docker content update

- kube-prereq.adoc
for prereqs change https://github.com/OpenLiberty/guides-common/issues/292
> Prereqs update

- guide_prereqs.json
- kube-prereq.adoc
> Merge qa to master: Prerequisites update

- guide_prereqs.json
Make OpenJ9 as the recommended prereq JDK
> Gkwan ibm patch 1

- gitclone.adoc
#343 for jdk prereq
#347 for translation of clone command
> Merge qa to master: translation of clone and jdk prereq

- README.md
- guide_tags.json
> Merge qa to master: Make security a visiable tag

- guide_tags.json
> Merge qa to master: add guides to the tags

- guide_tags.json
> Merge qa to master: add tags for guide-cloud-google

- guide_categories.json
- guide_tags.json
add the new reactive messaging guide to tags
> Merge qa to master: update tags

- guide_categories.json
- guide_tags.json
> Merge qa to master: update categories

- guide_categories.json
- guide_tags.json
> Merge qa to master: update tags and categories for the reactive testing guide

- devmode-start.adoc
- devmode-test.adoc
From: https://github.com/OpenLiberty/draft-guide-reactive-service-testing/issues/42#issuecomment-622066754
> Dev mode rewrite

- ol-docker-pull.adoc
- ol-kernel-docker-pull.adoc
Issue: https://github.com/OpenLiberty/guides-common/issues/439
> add adoc for pulling latest OL image

- ol-docker-pull.adoc
- ol-kernel-docker-pull.adoc
> Merge qa to master: Update ol-kernel-docker-pull.adoc

- gitclone.adoc
- guide_categories.json
- guide_tags.json
Issues: https://github.com/OpenLiberty/guides-common/issues/450, https://github.com/OpenLiberty/guides-common/issues/462
PR: #468
> Merge qa to master:  Add docker desktop check for k8s

- devmode-quit.adoc
- devmode-start.adoc
- kube-start.adoc
- mvnbuild.adoc
- mvnverify.adoc
- twyb-end.adoc
- Addressed Issues outlined here: https://github.com/OpenLiberty/guides-common/issues/455
> update from shell to cmd line

- kube-prereq.adoc
address https://github.com/OpenLiberty/guide-kubernetes-microprofile-health/issues/74
> Add kubectl instructions.

- gitclone.adoc
- guide_tags.json
> Merge qa to master: add install kubectl instruction 

- guide_categories.json
- guide_tags.json
- add tags for the microprofile-reactive-messaging-rest-integration guide
- add the microprofile-reactive-messaging-rest-integration guide to the reactive category
> Merge qa to master: add tags and category for the microprofile-reactive-messaging-rest-integration guide

- CONTRIBUTING.md
> Merge qa to master: Add contributing file (#499)

- guide_categories.json
- guide_tags.json
for new guides
- microprofile-reactive-messaging-acknowledgment
- reactive-rest-client
> Update categories and tags

- CONTRIBUTING.md
- guide_tags.json
> Merge qa to master: Update categories and tags for new guides

- devmode-build.adoc
- devmode-quit.adoc
- devmode-start.adoc
https://github.com/OpenLiberty/draft-guide-social-login/issues/50
> ID feedback

- guide_categories.json
- guide_tags.json
add social-media-login guide to categories and tags
> Merge qa to master: add social-media-login guide

- guide_categories.json
> Merge qa to master: add cd finsih comment

- devmode-start.adoc
- twyb-intro.adoc
> Merge qa to master: add cd start command

- guide_categories.json
- guide_tags.json
update for the new cloud-openshift-operator guide
> Update guide_categories.jsonn and tags.json

- devmode-start-cd.adoc
- devmode-start.adoc
update for the new cloud-openshift-operator guide
#528
> Merge qa to master: update category and tags

- devmode-test.adoc
See https://github.com/OpenLiberty/draft-guide-mongodb/issues/55
> id feedback update

- devmode-start-cd.adoc
- addressed couple feedback from https://github.com/OpenLiberty/draft-guide-mongodb/issues/55
> Merge qa to master: fix ID feedback

- devmode-quit.adoc
- devmode-test.adoc
`enter`/`return` to `enter/return`
> Merge qa to master: revert changes

- devmode-test.adoc
> Merge qa to master: Update ol-kernel-docker-pull.adoc 

- guide_tags.json
- add reactive-messaging-sse guide
> Update json files for reactive-messaging-sse guide

- guide_categories.json
- guide_tags.json
update the tags and categories json files
> Add the new Reactive SSE guide

- devmode-lmp33-start-cd.adoc
- devmode-lmp33-start.adoc
> Merge qa to master: add the new Reactive SSE guide

- cloud-hosted/new-terminal.md
The new-terminal.md is the additional instruction for the cloud-hosted-guide.
> Merge qa to master: Create new-terminal.md

- guide_categories.json
- guide_tags.json
add the new mongodb-intro guide
> Update guide_tags.json and categories

- cloud-hosted/gitclone.adoc
- cloud-hosted/new-terminal.md
> Merge qa to master: add the new mongodb-intro guide

- guide_categories.json
rearrange the order of the Persisten categories
> Merge qa to master: Update guide_categories.json

- .github/workflows/daily-build.yml
- .github/workflows/docker-daily-test.yml
- .github/workflows/docker-guides.json
- .github/workflows/drafts-to-test.json
- .github/workflows/get-builds.py
- .github/workflows/get-docker-guides.py
- .github/workflows/get-repos.py
- .github/workflows/pre-daily-build.yml
- .github/workflows/slack-alert.py
- cloud-hosted/gitclone.adoc
- cloud-hosted/new-terminal.md
synchronize the files in the master branch to the dev branch
> Sync dev with master

- .github/workflows/docker-daily-test.yml
- .github/workflows/pre-daily-build.yml
> Merge qa to master: Echo build level and check for no builds

- .github/workflows/docker-daily-test.yml
Missed to update the docker-daily-test.yml to use master
> Update docker-daily-test.yml to use master instead of gh-actions

- .github/workflows/docker-daily-test.yml
- .github/workflows/pre-daily-build.yml
> Merge qa to master: add new contract testing guide

- .github/workflows/license.yml
- pr-checker/checker.py
- pr-checker/checker.sh
- pr-checker/deny_list.json
- pr-checker/linters/.dockerfilelintrc
- pr-checker/linters/.yaml-lint.yml
- pr-checker/linters/config/java.header
- pr-checker/linters/sun_checks.xml
- pr-checker/warning_list.json
* converting to python
* denylist and warninglist regex
* regex for copyright license
* license and line length for java
* adoc checker
* update to pr checker
* add line number for errors
* fix
* formatting text edit
* fix copyright year error
* Update checker.py
* html license check
* Update checker.py
* move PR to sub directory
* super-linter starter config
* removed javadoc checker
* Update java.header
* Update java.header
* Update sun_checks.xml
* fixing regex
* removed redundant functions
* using script for workflow
* Update checker.sh
* Update sun_checks.xml
* fixed syntax error
* add action to update license yearly
* fix syntax
* Update license.yml
* Update license.yml
* Update license.yml
* Update license.yml
* Update license.yml
* Update license.yml
* Update license.yml
* add …
> Merge qa to master: PR checker (#556)

- pr-checker/checker.py
* converting to python
* denylist and warninglist regex
* regex for copyright license
* license and line length for java
* adoc checker
* update to pr checker
* add line number for errors
* fix
* formatting text edit
* fix copyright year error
* Update checker.py
* html license check
* Update checker.py
* move PR to sub directory
* super-linter starter config
* removed javadoc checker
* Update java.header
* Update java.header
* Update sun_checks.xml
* fixing regex
* removed redundant functions
* using script for workflow
* Update checker.sh
* Update sun_checks.xml
* fixed syntax error
* add action to update license yearly
* fix syntax
* Update license.yml
* Update license.yml
* Update license.yml
* Update license.yml
* Update license.yml
* Update license.yml
* Update license.yml
* add …
> Merge qa to master: PR checker update (#586)

- pr-checker/checker.py
Fixes output when there are only warnings.
Fixes license validation.
> PR checker minor fixes

- pr-checker/checker.py
> Merge qa to master: Update checker.py

- cloud-hosted/before-start-information.md
- cloud-hosted/gitclone.adoc
- cloud-hosted/new-terminal.md
Updating the cloud-hosted guide-commons to match the ID review
> Updates to cloud-hosted guide-commons

- cloud-hosted/before-start-information.md
- cloud-hosted/gitclone.adoc
- cloud-hosted/new-terminal.md
> Merge qa to master: update md files for cloud-hosted guides

- pr-checker/checker.py
- pr-checker/linters/sun_checks.xml
> Only allow tags with "visible" field

- pr-checker/checker.py
- pr-checker/linters/sun_checks.xml
* syntax typo
* error checking and only allow visible tags
> Merge qa to master: Only allow tags with "visible" field (#599)

- pr-checker/linters/sun_checks.xml
Disabled HiddenField check and MemberName check
> disabled some checks

- pr-checker/checker.py
- pr-checker/linters/sun_checks.xml
> Merge qa to master: disable some pr checks

- pr-checker/checker.sh
- pr-checker/linters/sun_checks.xml
> Merge qa to master: check non-deleted files only

- .github/workflows/docker-daily-test.yml
- pr-checker/checker.sh
> Merge qa to master: update daily docker test

- pr-checker/checker.sh
- pr-checker/deny_list.json
- pr-checker/warning_list.json
1. Best practices for script
2. Warning for using "I"
3. Changed log level of "master" from `error` to `warning`
> Update to PR checker

- pr-checker/checker.sh
- pr-checker/deny_list.json
- pr-checker/warning_list.json
* best practice for checker and checks for I
* Update warning_list.json
* Update deny_list.json
> Merge qa to master: Update to PR checker (#611)

- pr-checker/checker.py
> PR checker

- ol-full-docker-pull.adoc
- pr-checker/checker.py
PR: #616 
- Fix tag checking bug
> Merge qa to master: update PR checker

- cloud-hosted/new-terminal.md
remove the navigate/cd instructions
for step 4 issue from OpenLiberty/cloud-hosted-guide-converter#133
> Merge qa to master: Update new-terminal.md (#620)

- pr-checker/checker.py
- Change regex to only check for lines starting with `- `
> PR checker fix 

- pr-checker/checker.py
> Merge qa to master: only checks for lines starting with `- ` (#624)

- pr-checker/checker.py
- pr-checker/checker.sh
- pr-checker/rules.json
* Update checker.py
* add exceptions functionality
* rules file and error fix
> Merge qa to master: Update PR checker (#626)

- .github/workflows/daily-build.yml
> Update daily-build.yml (#633)

- .github/workflows/daily-build.yml
missing double quote character
> Update daily-build.yml (#635)

- pr-checker/linters/.htmlhintrc
> Merge qa to master: Update .htmlhintrc (#640)

- pr-checker/linters/.htmlhintrc
> Merge qa to master: Update .htmlhintrc

- .github/workflows/daily-build.yml
- .github/workflows/docker-daily-test.yml
> Merge qa to master: Switch daily builds to JDK 11 only (#646)

- .github/workflows/daily-build.yml
- .github/workflows/docker-daily-test.yml
- .github/workflows/pre-daily-build.yml
* Update daily-build.yml
* Update docker-daily-test.yml
* Adjust for automatic trigger
Co-authored-by: Austin Seto <austin.seto@ibm.com>
> Merge qa to master: Make JDK level as an input (#648)

- .github/workflows/daily-build.yml
- .github/workflows/docker-daily-test.yml
update the jdk level input to a value instead of a matrix
> Merge qa to master: update the jdk level input

- .github/workflows/daily-build.yml
- .github/workflows/docker-daily-test.yml
* Update daily-build.yml
* Update docker-daily-test.yml
> Merge qa to master: fix jdk level input (#651)

- .github/workflows/pre-daily-build.yml
fix jdk playload to support java-level input
> Merge qa to master: Update pre-daily-build.yml (#653)

- gitclone.adoc
* Update gitclone.adoc
* Update gitclone.adoc
* Update gitclone.adoc
* Update gitclone.adoc
Co-authored-by: Steven Zvonek <szvonek@us.ibm.com>
> Merge qa to main - Update gitclone.adoc (#656)

- gitclone.adoc
fixed an error to rerun the daily build
> Merge qa to main: update get_builds.py

- cloud-hosted-guides.json
enable 10 guides for cloud-hosted
> Merge qa to prod - Create cloud-hosted-guides.json (#663)

- cloud-hosted-guides.json
> Merge qa to prod - disable linter for unused import

- .github/workflows/daily-build.yml
Add an option to select the branch when manually testing a guide
> Branch selector

- .github/workflows/daily-build.yml
* Update daily-build.yml to add an option so when manually run a daily build test, can change which branch it runs on.
> Merge qa to prod - Branch selector (#670)

- .github/workflows/daily-build.yml
add skills-network-kube-setup.adoc
> Merge qa to prod: adoc instruction of kubenetes set up  for cloud-hosted guides

- skills-network-kube-setup.adoc
comment the license information
> Merge qa to prod:  update skills-network-kube-setup.adoc

- guide-redirects.properties
fix the issue  https://github.com/OpenLiberty/openliberty.io/issues/179 and relate to #81
> Merge qa to prod - Create guide-redirects.properties (#680)
